### ISSUE TITLE
Assessments should be numbered

### ISSUE THREAD

**Issue by Fancien** [FAIR-CA-indicators/fair-ca-indicators-frontend#13]
One comment was that the assessments should be numbered, for example (very rough example): 

<img width="506" alt="image" src="https://user-images.githubusercontent.com/29706637/234724390-a108e867-95d7-42c9-9330-4f252232d80a.png">

If this is implemented, it needs to integrate with issues #10 and #11

**Comment by Gebbi8** [comment]
implemented
